const W=1280,H=720, G=2300;
const rnd=(a,b)=>a+Math.random()*(b-a), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const weapons={
  pistol:{name:'PISTOL', dmg:36, mag:12, reserve:72, rate:.28, spread:.025, recoil:150, speed:1120, reload:1.05, auto:false, pellets:1},
  rifle:{name:'RIFLE', dmg:18, mag:30, reserve:150, rate:.075, spread:.06, recoil:88, speed:1380, reload:1.45, auto:true, pellets:1},
  shotgun:{name:'SHOTGUN', dmg:17, mag:6, reserve:42, rate:.55, spread:.18, recoil:270, speed:980, reload:1.65, auto:false, pellets:7}
};
export class Game{
  constructor(canvas,input,audio){ this.c=canvas; this.ctx=canvas.getContext('2d',{alpha:false}); this.input=input; this.audio=audio; this.dpr=1; this.resize(); this.reset(); }
  reset(){
    this.state='play'; this.t=0; this.slow=0; this.flash=0; this.shake=0; this.camX=0; this.msg='WAVE INCOMING!'; this.msgT=2.0; this.radio='INSTRUCTOR: MOVE! MOVE!'; this.radioT=0;
    this.score=0; this.best=Number(localStorage.stickBootBestSide||0); this.wave=0; this.combo=1; this.comboT=0;
    this.player={x:170,y:470,vx:0,vy:0,w:34,h:96,hp:100,maxHp:100,face:1,ground:false,fireT:0,reloadT:0,reloading:false,weapon:'pistol',ammo:{pistol:{mag:12,res:72},rifle:{mag:30,res:150},shotgun:{mag:6,res:42}},inv:0};
    this.bullets=[]; this.parts=[]; this.enemies=[]; this.pickups=[]; this.limbs=[]; this.muzzles=[]; this.casings=[]; this.trails=[];
    this.platforms=[{x:0,y:580,w:2200,h:180},{x:380,y:500,w:145,h:22},{x:610,y:445,w:170,h:24},{x:900,y:505,w:145,h:22},{x:1180,y:455,w:175,h:24},{x:1480,y:505,w:185,h:22}];
    this.covers=[{x:320,y:520,w:86,h:60,type:'sandbags'},{x:760,y:515,w:75,h:65,type:'crate'},{x:1060,y:520,w:112,h:60,type:'sandbags'},{x:1390,y:515,w:78,h:65,type:'crate'}];
    this.nextWave();
  }
  resize(){ const r=this.c.getBoundingClientRect(); this.dpr=Math.min(2,window.devicePixelRatio||1); this.c.width=Math.max(2,r.width*this.dpr|0); this.c.height=Math.max(2,r.height*this.dpr|0); }
  pause(text='PAUSED'){ if(this.state==='play'){ this.state='pause'; this.msg=text; this.msgT=999; } }
  resume(){ if(this.state==='pause'){ this.state='play'; this.msg='MOVE!'; this.msgT=.8; } }
  nextWave(){ this.wave++; this.msg=this.wave===1?'WAVE INCOMING!':'ВОЛНА ЗАЧИЩЕНА'; this.msgT=1.55; this.radio='INSTRUCTOR: WAVE '+this.wave+' INCOMING!'; this.radioT=2.5; const n=4+this.wave*2; for(let i=0;i<n;i++) this.spawnEnemy(900+i*145+rnd(0,260)); }
  spawnEnemy(x){ const roll=Math.random(), type=roll<.18+this.wave*.015?'heavy':roll<.52?'runner':'soldier'; const s={soldier:[70,90,110,18,'#33261d'],runner:[48,150,85,14,'#5b3322'],heavy:[165,62,150,27,'#2b2b30']}[type]; this.enemies.push({type,x,y:470,vx:0,vy:0,w:s[3],h:s[2],hp:s[0],maxHp:s[0],speed:s[1],color:s[4],face:-1,ground:false,atk:0,stun:0,dead:false,phase:rnd(0,6)}); }
  tick(dt){ const portrait=innerHeight>innerWidth; if(portrait){this.draw();return;} if(this.input.started && this.state==='pause') this.resume(); if(this.state==='play') this.update(dt*(this.slow>0?.38:1)); if(this.slow>0)this.slow-=dt; this.draw(); this.input.reload=false; this.input.switch=false; }
  update(dt){ this.t+=dt; this.radioT-=dt; if(this.radioT<0){ const r=['INSTRUCTOR: MOVE! MOVE!','INSTRUCTOR: RELOAD!','INSTRUCTOR: USE COVER!','RANGE CONTROL: KEEP FIRING!']; this.radio=r[(Math.random()*r.length)|0]; this.radioT=rnd(2.5,4.5);} this.msgT-=dt; this.comboT-=dt; if(this.comboT<=0)this.combo=1;
    const p=this.player; p.inv-=dt; p.fireT-=dt; if(this.input.consume('switch')) this.switchWeapon(); if(this.input.consume('reload')) this.reload();
    if(p.reloading){ p.reloadT-=dt; if(p.reloadT<=0) this.finishReload(); }
    const ax=this.input.x*1500; p.vx+=ax*dt; p.vx*=Math.pow(.0008,dt); p.vx=clamp(p.vx,-360,360); if(Math.abs(this.input.x)>.05)p.face=Math.sign(this.input.x);
    if(this.input.jump && p.ground){ p.vy=-780; p.ground=false; this.audio.tone('triangle',220,.05,.04,80); }
    p.vy+=G*dt; this.moveBody(p,dt);
    if(!this.input.fire) p.fireHeld=false; if(this.input.fire) this.tryFire();
    this.updateEnemies(dt); this.updateBullets(dt); this.updateFX(dt); this.pickCollisions();
    if(this.enemies.length===0) this.nextWave();
    this.camX=clamp(p.x-360,0,900); this.shake*=Math.pow(.02,dt); this.flash*=Math.pow(.01,dt);
  }
  switchWeapon(){ const order=['pistol','rifle','shotgun']; const i=(order.indexOf(this.player.weapon)+1)%order.length; this.player.weapon=order[i]; this.msg=weapons[this.player.weapon].name; this.msgT=.7; this.audio.click(); }
  reload(){ const p=this.player, a=p.ammo[p.weapon], w=weapons[p.weapon]; if(p.reloading||a.mag>=w.mag||a.res<=0)return; p.reloading=true; p.reloadT=w.reload; this.audio.reload(); this.msg='RELOAD!'; this.msgT=.65; }
  finishReload(){ const p=this.player, a=p.ammo[p.weapon], w=weapons[p.weapon]; const need=w.mag-a.mag, take=Math.min(need,a.res); a.mag+=take; a.res-=take; p.reloading=false; }
  tryFire(){ const p=this.player,w=weapons[p.weapon],a=p.ammo[p.weapon]; if(p.reloading||p.fireT>0)return; if(a.mag<=0){ this.audio.click(); p.fireT=.18; if(a.res>0)this.reload(); return; } if(!w.auto && p.fireHeld){return;} p.fireHeld=true; a.mag--; p.fireT=w.rate; const ax=p.face, ay=clamp(this.input.aimY*.35,-.38,.38); p.vx-=ax*w.recoil; this.shake+=p.weapon==='shotgun'?12:7; this.flash=.22; this.audio.shot(p.weapon); const mx=p.x+ax*28, my=p.y-p.h*.58+ay*42; this.muzzles.push({x:mx,y:my,life:.06,face:ax}); this.casings.push({x:mx-ax*8,y:my+4,vx:-ax*rnd(120,260),vy:rnd(-220,-90),r:rnd(0,6),vr:rnd(-18,18),life:1}); for(let i=0;i<w.pellets;i++){ const ang=ay+rnd(-w.spread,w.spread); this.bullets.push({x:mx,y:my,vx:ax*w.speed*Math.cos(ang),vy:w.speed*Math.sin(ang),life:.85,dmg:w.dmg,from:'p',crit:Math.abs(ang-ay)<.025 && Math.random()<.28}); this.trails.push({x1:mx-ax*16,y1:my,x2:mx+ax*100,y2:my+ang*100,life:.08}); } }
  moveBody(o,dt){ o.x+=o.vx*dt; this.blockX(o); o.y+=o.vy*dt; o.ground=false; for(const pl of this.platforms){ if(o.x+o.w/2>pl.x&&o.x-o.w/2<pl.x+pl.w&&o.y>pl.y&&o.y-o.h<pl.y+pl.h && o.vy>=0){ o.y=pl.y; o.vy=0; o.ground=true; } } if(o.y>900){ o.y=470; o.vy=0; o.hp-=20; } }
  blockX(o){ for(const c of this.covers){ if(o.x+o.w/2>c.x&&o.x-o.w/2<c.x+c.w&&o.y>c.y&&o.y-o.h<c.y+c.h){ if(o.vx>0)o.x=c.x-o.w/2; else if(o.vx<0)o.x=c.x+c.w+o.w/2; o.vx=0; } } }
  updateEnemies(dt){ const p=this.player; for(const e of this.enemies){ e.stun-=dt; const dir=Math.sign(p.x-e.x)||1; e.face=dir; const dist=Math.abs(p.x-e.x); if(e.stun<0){ e.vx+=dir*e.speed*8*dt; e.vx=clamp(e.vx,-e.speed,e.speed); } if(dist<e.w+34 && Math.abs(p.y-e.y)<90){ e.atk-=dt; e.vx*=.55; if(e.atk<=0){ e.atk=e.type==='runner'?.48:.7; if(p.inv<=0){ p.hp-=e.type==='heavy'?22:12; p.inv=.35; this.shake+=10; this.audio.hit(); this.blood(p.x,p.y-55,8,'#891d17'); if(p.hp<=0)this.gameOver(); } } } if(e.ground && dist>90 && Math.random()<.008+this.wave*.001) e.vy=-620; e.vy+=G*dt; e.vx*=Math.pow(.001,dt); this.moveBody(e,dt); }
    this.enemies=this.enemies.filter(e=>!e.dead);
  }
  updateBullets(dt){ for(const b of this.bullets){ b.x+=b.vx*dt; b.y+=b.vy*dt; b.life-=dt; let hit=false; for(const c of this.covers){ if(b.x>c.x&&b.x<c.x+c.w&&b.y>c.y&&b.y<c.y+c.h){ this.sparks(b.x,b.y,8); hit=true; break; } } if(!hit){ for(const e of this.enemies){ if(b.from==='p'&&b.x>e.x-e.w/2&&b.x<e.x+e.w/2&&b.y>e.y-e.h&&b.y<e.y){ const dmg=b.dmg*(b.crit?2.2:1); e.hp-=dmg; e.vx+=Math.sign(b.vx)*80; e.stun=.08; this.blood(b.x,b.y,b.crit?18:9,b.crit?'#ff2d25':'#9b1713'); this.audio.hit(); if(b.crit){this.msg='CRITICAL!';this.msgT=.45;this.score+=15;} if(e.hp<=0)this.killEnemy(e); hit=true; break; } } } if(hit)b.life=-1; } this.bullets=this.bullets.filter(b=>b.life>0&&b.x>-100&&b.x<2300&&b.y>-100&&b.y<800); }
  killEnemy(e){ e.dead=true; this.combo=Math.min(8,this.combo+.35); this.comboT=2.2; const add=Math.round((e.type==='heavy'?180:e.type==='runner'?95:120)*this.combo); this.score+=add; this.audio.death(); this.shake+=14; if(e.type==='heavy')this.slow=.35; this.limbBurst(e); if(Math.random()<.35) this.pickups.push({x:e.x,y:e.y-30,type:Math.random()<.55?'ammo':'med',vy:-250,life:12,phase:rnd(0,6)}); }
  limbBurst(e){ const segs=['head','arm','arm','leg','leg','torso']; for(const s of segs)this.limbs.push({x:e.x+rnd(-8,8),y:e.y-e.h*rnd(.25,.85),vx:rnd(-250,250),vy:rnd(-520,-120),r:rnd(0,6),vr:rnd(-14,14),life:3,type:s,color:e.color}); this.blood(e.x,e.y-e.h*.55,24,'#8f1713'); }
  updateFX(dt){ const arrs=[this.parts,this.muzzles,this.casings,this.trails,this.limbs,this.pickups]; for(const arr of arrs)for(const o of arr){ o.life-=dt; if(o.vy!=null){ o.vy+=G*.55*dt; o.x+=(o.vx||0)*dt; o.y+=o.vy*dt; if(o.y>568){o.y=568;o.vy*=o.type==='med'||o.type==='ammo'?-.25:-.18;o.vx=(o.vx||0)*.72;} } if(o.r!=null)o.r+=(o.vr||0)*dt; } this.parts=this.parts.filter(o=>o.life>0); this.muzzles=this.muzzles.filter(o=>o.life>0); this.casings=this.casings.filter(o=>o.life>0); this.trails=this.trails.filter(o=>o.life>0); this.limbs=this.limbs.filter(o=>o.life>0); this.pickups=this.pickups.filter(o=>o.life>0); }
  blood(x,y,n,color){ for(let i=0;i<n;i++)this.parts.push({x,y,vx:rnd(-260,260),vy:rnd(-380,70),life:rnd(.3,1.1),r:rnd(2,5),color}); }
  sparks(x,y,n){ for(let i=0;i<n;i++)this.parts.push({x,y,vx:rnd(-260,260),vy:rnd(-260,80),life:rnd(.15,.45),r:rnd(1,3),color:'#ffd166'}); this.audio.tone('square',900,.025,.035,-200); }
  pickCollisions(){ const p=this.player; for(const q of this.pickups){ if(Math.abs(q.x-p.x)<42&&Math.abs(q.y-(p.y-50))<70){ if(q.type==='med')p.hp=Math.min(p.maxHp,p.hp+35); else for(const k of Object.keys(weapons))p.ammo[k].res+= k==='shotgun'?8: k==='rifle'?45:24; q.life=-1; this.score+=25; this.audio.pickup(); this.msg=q.type==='med'?'+MEDKIT':'+AMMO'; this.msgT=.7; } } }
  gameOver(){ this.state='over'; localStorage.stickBootBestSide=Math.max(this.best,this.score); this.best=Number(localStorage.stickBootBestSide); this.msg='MISSION FAILED'; this.msgT=999; }
  draw(){ const ctx=this.ctx,d=this.dpr,sw=this.c.width/d,sh=this.c.height/d; ctx.setTransform(d,0,0,d,0,0); ctx.fillStyle='#16120b'; ctx.fillRect(0,0,sw,sh); const sx=sw/W, sy=sh/H; ctx.save(); ctx.scale(sx,sy); const ox=(Math.random()-.5)*this.shake, oy=(Math.random()-.5)*this.shake; ctx.translate(-this.camX+ox,oy); this.world(ctx); ctx.restore(); ctx.save(); ctx.scale(sx,sy); this.hud(ctx); ctx.restore(); }
  world(ctx){ const grad=ctx.createLinearGradient(0,0,0,H); grad.addColorStop(0,'#7aa0b7'); grad.addColorStop(.42,'#d7b36d'); grad.addColorStop(.43,'#a97837'); grad.addColorStop(1,'#6a431e'); ctx.fillStyle=grad; ctx.fillRect(this.camX,0,W+80,H); ctx.strokeStyle='rgba(255,255,255,.15)'; for(let x=-80;x<2300;x+=80){ctx.beginPath();ctx.moveTo(x,580);ctx.lineTo(x+35,720);ctx.stroke();} this.decor(ctx); for(const pl of this.platforms)this.drawPlatform(ctx,pl); for(const c of this.covers)this.drawCover(ctx,c); for(const q of this.pickups)this.drawPickup(ctx,q); for(const tr of this.trails){ctx.globalAlpha=tr.life/.08; ctx.strokeStyle='#fff0a9'; ctx.lineWidth=2; ctx.beginPath();ctx.moveTo(tr.x1,tr.y1);ctx.lineTo(tr.x2,tr.y2);ctx.stroke();ctx.globalAlpha=1;} for(const b of this.bullets){ctx.fillStyle='#fff6b0';ctx.beginPath();ctx.arc(b.x,b.y,3,0,7);ctx.fill();} for(const e of this.enemies)this.drawStick(ctx,e,false); this.drawStick(ctx,this.player,true); for(const m of this.muzzles)this.drawMuzzle(ctx,m); for(const c of this.casings)this.drawCasing(ctx,c); for(const l of this.limbs)this.drawLimb(ctx,l); for(const p of this.parts)this.drawParticle(ctx,p); }
  decor(ctx){ ctx.fillStyle='rgba(30,20,10,.25)'; for(let x=80;x<2100;x+=230){ctx.fillRect(x,552,90,7); ctx.fillRect(x+36,505,8,48); ctx.strokeStyle='#c53030'; ctx.lineWidth=5; ctx.beginPath();ctx.arc(x+40,492,18,0,7);ctx.stroke();ctx.lineWidth=2;ctx.beginPath();ctx.arc(x+40,492,7,0,7);ctx.stroke();} ctx.fillStyle='rgba(45,35,25,.42)'; ctx.fillRect(1540,270,18,310); ctx.fillRect(1630,270,18,310); ctx.fillRect(1506,270,176,18); ctx.fillRect(1530,230,128,42); }
  drawPlatform(ctx,p){ ctx.fillStyle='#6b4524'; ctx.fillRect(p.x,p.y,p.w,p.h); ctx.fillStyle='#8b5a2b'; ctx.fillRect(p.x,p.y,p.w,6); }
  drawCover(ctx,c){ if(c.type==='crate'){ctx.fillStyle='#6d4726';ctx.fillRect(c.x,c.y,c.w,c.h);ctx.strokeStyle='#2d1d10';ctx.lineWidth=4;ctx.strokeRect(c.x+4,c.y+4,c.w-8,c.h-8);ctx.beginPath();ctx.moveTo(c.x+8,c.y+8);ctx.lineTo(c.x+c.w-8,c.y+c.h-8);ctx.moveTo(c.x+c.w-8,c.y+8);ctx.lineTo(c.x+8,c.y+c.h-8);ctx.stroke();} else { for(let i=0;i<3;i++){ctx.fillStyle=i%2?'#9b7440':'#b2874e'; round(ctx,c.x+i*7,c.y+38-i*18,c.w-14,20,10); ctx.fill(); ctx.strokeStyle='rgba(40,25,10,.35)'; ctx.stroke();}} }
  drawStick(ctx,o,player){ const x=o.x,y=o.y,h=o.h||96, face=o.face||1, run=Math.sin(this.t*12+(o.phase||0))*10*(Math.abs(o.vx||0)>40?1:.15); ctx.save(); ctx.lineCap='round'; ctx.lineJoin='round'; ctx.strokeStyle=player?'#141414':o.color; ctx.fillStyle=player?'#f4d07b':o.color; ctx.lineWidth=player?5:4; const headY=y-h+15; ctx.beginPath();ctx.arc(x,headY,12,0,7);ctx.fill();ctx.stroke(); ctx.beginPath();ctx.moveTo(x,headY+14);ctx.lineTo(x,y-45);ctx.stroke(); ctx.beginPath();ctx.moveTo(x,y-75);ctx.lineTo(x+face*24,y-62+this.input.aimY*22);ctx.lineTo(x+face*45,y-62+this.input.aimY*22);ctx.stroke(); ctx.strokeStyle='#222';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x+face*25,y-62+this.input.aimY*22);ctx.lineTo(x+face*58,y-61+this.input.aimY*22);ctx.stroke(); ctx.strokeStyle=player?'#141414':o.color; ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x,y-43);ctx.lineTo(x-12,y-12-run);ctx.lineTo(x-18,y);ctx.moveTo(x,y-43);ctx.lineTo(x+13,y-12+run);ctx.lineTo(x+21,y);ctx.stroke(); if(!player){ctx.fillStyle='#1d120d';ctx.fillRect(x-24,y-h-10,48,5);ctx.fillStyle='#d32922';ctx.fillRect(x-24,y-h-10,48*(o.hp/o.maxHp),5);} ctx.restore(); }
  drawMuzzle(ctx,m){ ctx.save();ctx.translate(m.x,m.y);ctx.scale(m.face,1);ctx.fillStyle='#fff3a8';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(30,-9);ctx.lineTo(22,0);ctx.lineTo(30,9);ctx.closePath();ctx.fill();ctx.restore(); }
  drawCasing(ctx,c){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.r);ctx.fillStyle='#d7af48';ctx.fillRect(-4,-2,8,4);ctx.restore();}
  drawParticle(ctx,p){ctx.globalAlpha=clamp(p.life,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();ctx.globalAlpha=1;}
  drawLimb(ctx,l){ctx.save();ctx.translate(l.x,l.y);ctx.rotate(l.r);ctx.strokeStyle=l.color;ctx.fillStyle=l.color;ctx.lineWidth=4; if(l.type==='head'){ctx.beginPath();ctx.arc(0,0,10,0,7);ctx.fill();ctx.stroke();}else{ctx.beginPath();ctx.moveTo(-12,0);ctx.lineTo(12,0);ctx.stroke();}ctx.restore();}
  drawPickup(ctx,q){ const s=1+Math.sin(this.t*7+q.phase)*.12; ctx.save();ctx.translate(q.x,q.y);ctx.scale(s,s); if(q.type==='med'){ctx.fillStyle='#f5f2e8';round(ctx,-17,-13,34,26,6);ctx.fill();ctx.fillStyle='#cc2929';ctx.fillRect(-4,-10,8,20);ctx.fillRect(-11,-3,22,7);}else{ctx.fillStyle='#8b5a2b';round(ctx,-18,-14,36,28,5);ctx.fill();ctx.fillStyle='#ffd166';ctx.fillRect(-11,-4,22,8);}ctx.restore();}
  hud(ctx){ const p=this.player,w=weapons[p.weapon],a=p.ammo[p.weapon]; ctx.fillStyle='rgba(0,0,0,.45)';round(ctx,20,18,360,88,16);ctx.fill(); ctx.fillStyle='#351714';round(ctx,38,42,210,20,10);ctx.fill();ctx.fillStyle='#e3362b';round(ctx,38,42,210*(p.hp/p.maxHp),20,10);ctx.fill(); ctx.fillStyle='#ffe8a5';ctx.font='800 20px system-ui';ctx.fillText(`HP ${Math.max(0,p.hp|0)}`,44,35);ctx.fillText(`WAVE ${this.wave}`,270,36);ctx.fillText(`SCORE ${this.score}`,44,82); ctx.textAlign='right';ctx.fillText(`BEST ${this.best}`,1260,34);ctx.fillText(`${w.name}  ${a.mag}/${a.res}`,1260,66); if(p.reloading){ctx.fillStyle='rgba(255,255,255,.25)';round(ctx,925,80,300,16,8);ctx.fill();ctx.fillStyle='#ffe08a';round(ctx,925,80,300*(1-p.reloadT/w.reload),16,8);ctx.fill();} if(this.combo>1){ctx.textAlign='center';ctx.fillStyle='#ffcf55';ctx.font='900 28px system-ui';ctx.fillText(`COMBO x${this.combo.toFixed(1)}`,640,56);} ctx.textAlign='center'; if(this.msgT>0){ctx.fillStyle='rgba(0,0,0,.38)';round(ctx,440,95,400,54,18);ctx.fill();ctx.fillStyle='#fff2b9';ctx.font='900 34px system-ui';ctx.fillText(this.msg,640,133);} ctx.fillStyle='rgba(0,0,0,.55)';round(ctx,350,668,580,34,12);ctx.fill();ctx.fillStyle='#e7d08a';ctx.font='800 18px monospace';ctx.fillText(this.radio,640,691); if(this.state==='pause'||this.state==='over'){ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffe8a5';ctx.font='900 54px system-ui';ctx.fillText(this.state==='over'?'MISSION FAILED':'PAUSED',640,260);ctx.font='800 26px system-ui';ctx.fillText(`Score: ${this.score}   Best: ${this.best}`,640,310);ctx.fillStyle='#8a351d';round(ctx,520,350,240,72,24);ctx.fill();ctx.fillStyle='#fff2bd';ctx.font='900 28px system-ui';ctx.fillText('RESTART',640,397); if(this.input.fire||this.input.jump){this.reset();}} }
}
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
